name: ci

on:
  pull_request:
    branches: [main]
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run Unit tests
        run: npm run test:ci
#       - name: Run E2E with cypress
#         run: npm run test:e2e
      - name: Build app
        run: npm run build
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fire_and_ice-${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}
          path: ./dist/fire_and_ice

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: fire_and_ice-${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}
          path: './build'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
